(in-package :bermuda)

(defparameter *player* nil)
(defparameter *score* 0)
(defparameter *lives* 0)
(defconstant +level-size+ 25600)

(defun build-level (n)
  (init-particles)
  (init-sprites)
  (dotimes (i (* n 1000))
    (random 1))
  (dotimes (i 150)
    (make-instance 'enemy-plane
                   :pos (v (random 15000) (random 600))))
  (setf *player* (make-instance 'player :pos (v 0 0))
        *map* (let ((map (make-array (/ +level-size+ 256) :initial-element nil)))
                (dotimes (x (/ +level-size+ 256))
                  (setf (aref map x) (random-elt (list (make-tile :image (tag 'grass))
                                                       (make-tile :image (tag 'land))
                                                       (make-tile :image (tag 'grass))))))
                map)))


(defun bermuda ()
  (with-pal (:fullscreenp t :title "Bermuda" :paths "data/")
    (set-cursor nil)
    (main-loop)))


(defun main-loop (&aux (score-display 0) (level 0))
  (setf *score* 0
        *lives* 3)
  (build-level level)
  (play-music (tag 'music) :loops t :volume 60)
  (event-loop ()
    (setf *view* (v-round (v (min (- (* +level-size+ 256) 800)
                                  (+ (vx *view*) 2))
                             (* (- (vy (pos-of *player*)) 300) .2f0))))

    (if (> *shake* 0)
        (with-transformation (:pos (if (> *shake* 0f0)
                                       (v (random (float *shake*)) (random (float *shake*)))
                                       (v 0 0)))
          (draw-screen)
          (decf *shake*))
        (draw-screen))
    (when (< score-display *score*)
      (incf score-display))
    (draw-text (prin1-to-string score-display) (v 5 -2) (tag 'font))
    (with-blend ()
      (if (< (hp-of *player*) 20)
          (set-blend-color (color 0 0 0 (random 255)))
          (set-blend-color (color 0 0 0 128)))
      (dotimes (i *lives*)
        (draw-image (tag 'plane) (v (- 700 (* i 40)) 25) :angle -45f0 :scale 0.5f0))
      (draw-image* (tag 'plane) (v 0 0) (v 730 2) (hp-of *player*) 50))))

;;(bermuda)