(in-package :bermuda)

(define-tags ufo (load-image "ufo.png" t)
  music (load-music "urafaerie+numberone.ogg")
  particle (load-image "particle.png")
  font (load-font "font")
  plane (load-image "plane.png" t)
  bullet (load-image "bullet.png")
  land (load-image "mass.png")
  grass (load-image "grass.png")
  explosion-1 (load-sample "explosion2.wav")
  explosion-2 (load-sample "h_gs1.WAV")
  shoot (load-sample "Gatling.wav" 8)
  horizon (load-image "horizon.png"))